# Generated by Django 4.2.5 on 2023-10-02 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0004_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="url",
        ),
    ]
