# Generated by Django 4.2.5 on 2023-10-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0008_alter_tier_height"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tier",
            old_name="height",
            new_name="thumbnail_height_1",
        ),
        migrations.AddField(
            model_name="tier",
            name="thumbnail_height_10",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tier",
            name="thumbnail_height_2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tier",
            name="thumbnail_height_3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tier",
            name="thumbnail_height_4",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tier",
            name="thumbnail_height_5",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tier",
            name="thumbnail_height_6",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tier",
            name="thumbnail_height_7",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tier",
            name="thumbnail_height_8",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tier",
            name="thumbnail_height_9",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
