# Generated by Django 4.2.5 on 2023-10-07 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0010_alter_tier_orginal_link_alter_user_tier"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="owner",
            new_name="owner_id",
        ),
    ]
