# Generated by Django 4.2.5 on 2023-10-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0013_rename_owner_id_image_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="time_created",
        ),
        migrations.AddField(
            model_name="image",
            name="original_image",
            field=models.BooleanField(default=False),
        ),
    ]
