# Generated by Django 4.2.5 on 2023-09-29 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user",
            new_name="profile",
        ),
    ]
