# Generated by Django 4.2.5 on 2023-09-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0003_rename_profile_user_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="url",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
