# Generated by Django 4.2.5 on 2023-10-07 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0009_rename_height_tier_thumbnail_height_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tier",
            name="orginal_link",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="task.tier",
            ),
        ),
    ]
