# Generated by Django 4.2.5 on 2023-10-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0011_rename_owner_image_owner_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
